# Generated by Django 4.0.6 on 2022-08-12 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0.0, verbose_name='Order ID')),
                ('cost_usd', models.DecimalField(decimal_places=3, default=0.0, max_digits=19, verbose_name='Cost in USD')),
                ('cost_rub', models.DecimalField(decimal_places=3, default=0.0, max_digits=19, verbose_name='Cost in RUB')),
                ('delivery_time', models.DateField(default=datetime.date(1970, 1, 1), verbose_name='Delivery Time')),
            ],
        ),
    ]
